version: '3.8'

services:
  # Frontend service
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    ports:
      - "8080:80"
    environment:
      - API_URL=http://backend:8000
    depends_on:
      - backend
    networks:
      - title-verification-network

  # Backend API service
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - ES_HOST=elasticsearch
      - ES_PORT=9200
      - EMBEDDING_MODEL=all-MiniLM-L6-v2
      - LOG_LEVEL=INFO
    depends_on:
      - elasticsearch
    networks:
      - title-verification-network
    volumes:
      - ./backend:/app
      - model-cache:/root/.cache/torch/sentence_transformers

  # Elasticsearch service
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.10.4
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ports:
      - "9200:9200"
    volumes:
      - elasticsearch-data:/usr/share/elasticsearch/data
    networks:
      - title-verification-network

  # Redis for caching (optional)
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    networks:
      - title-verification-network

networks:
  title-verification-network:
    driver: bridge

volumes:
  elasticsearch-data:
  model-cache: 